CREATE TABLE `t_order` (
                           `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单ID',
                           `order_no` VARCHAR(64) NOT NULL COMMENT '订单编号',
                           `user_id` BIGINT NOT NULL COMMENT '用户ID',
                           `order_status` TINYINT NOT NULL DEFAULT 0 COMMENT '订单状态：0-待支付 1-已支付 2-已发货 3-已完成 4-已取消 5-已退款',
                           `pay_status` TINYINT NOT NULL DEFAULT 0 COMMENT '支付状态：0-未支付 1-支付中 2-已支付 3-支付失败',
                           `total_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '订单总金额',
                           `discount_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '优惠金额',
                           `pay_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '实付金额',
                           `pay_channel` TINYINT DEFAULT NULL COMMENT '支付方式：1-微信 2-支付宝 3-银行卡',
                           `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
                           `pay_transaction_no` VARCHAR(128) DEFAULT NULL COMMENT '支付流水号',
                           `receiver_name` VARCHAR(64) DEFAULT NULL COMMENT '收货人姓名',
                           `receiver_phone` VARCHAR(20) DEFAULT NULL COMMENT '收货人手机号',
                           `receiver_province` VARCHAR(32) DEFAULT NULL COMMENT '收货省',
                           `receiver_city` VARCHAR(32) DEFAULT NULL COMMENT '收货市',
                           `receiver_district` VARCHAR(32) DEFAULT NULL COMMENT '收货区',
                           `receiver_detail` VARCHAR(256) DEFAULT NULL COMMENT '收货详细地址',
                           `delivery_company` VARCHAR(64) DEFAULT NULL COMMENT '物流公司',
                           `delivery_no` VARCHAR(64) DEFAULT NULL COMMENT '物流单号',
                           `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
                           `finish_time` DATETIME DEFAULT NULL COMMENT '完成时间',
                           `cancel_time` DATETIME DEFAULT NULL COMMENT '取消时间',
                           `cancel_reason` VARCHAR(256) DEFAULT NULL COMMENT '取消原因',
                           `remark` VARCHAR(512) DEFAULT NULL COMMENT '订单备注',
                           `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
                           `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除 1-已删除',
                           `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                           `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uk_order_no` (`order_no`),
                           KEY `idx_user_id` (`user_id`),
                           KEY `idx_order_status` (`order_status`),
                           KEY `idx_pay_time` (`pay_time`),
                           KEY `idx_create_time` (`create_time`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '订单表';
