server:
  port: 9001

spring:
  application:
    name: cc-service
  config:
    import:
      - optional:nacos:cc-service.yaml
      - optional:nacos:cc-service
  datasource:
    url: jdbc:mysql://192.168.235.101:3306/cc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.235.101:8848
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.235.101:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        timeout: 5000
        fail-fast: false
        max-retry: 3
        retry-time: 2000
        refresh-enabled: true
  data:
    redis:
      host: 192.168.235.101
      port: 6379
      password: redis
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000

mybatis-plus:
  mapper-locations: classpath:com/cccz/**/*.xml
  type-aliases-package: com.cccz.*.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: "%d{yyyyMMdd HH:mm:ss.SSS} %clr(%5p) [%thread] %clr([%logger{36}]){cyan} - %msg%n"
    dateformat: yyyyMMdd HH:mm:ss.SSS
  level:
    com.alibaba.nacos: WARN
    com.alibaba.cloud: WARN
    org.springframework: INFO
    com.cccz.order.dao: DEBUG